name: Build Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-arm-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install cross-compiler
      run: |
        sudo apt update
        sudo apt install -y build-essential gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
    
    - name: Build ARM64 terminal server
      run: |
        make -f makefile.terminal-server-aarch64 clean
        make -f makefile.terminal-server-aarch64 opt
    
    - name: Create release package
      run: |
        mkdir -p release-package
        cp wangemu-terminal-server-aarch64 release-package/
        cp setup-startup.sh release-package/
        cp start-wangemu.sh release-package/
        chmod +x release-package/*
        cd release-package
        zip -r ../wangemu-raspberry-pi-v${GITHUB_REF#refs/tags/}.zip *
        cd ..
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wangemu-raspberry-pi-package
        path: release-package/
        retention-days: 90
    
    - name: Upload release package to release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./wangemu-raspberry-pi-v${{ github.ref_name }}.zip
        asset_name: wangemu-raspberry-pi-${{ github.ref_name }}.zip
        asset_content_type: application/zip